DROP TABLE IF EXISTS billionaires;

CREATE TABLE billionaires (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  career VARCHAR(250) DEFAULT NULL
);

INSERT INTO billionaires (first_name, last_name, career) VALUES
  ('Aliko', 'Dangote', 'Billionaire Industrialist'),
  ('Bill', 'Gates', 'Billionaire Tech Entrepreneur'),
  ('Folrunsho', 'Alakija', 'Billionaire Oil Magnate');

CREATE TABLE RegistryOffsetProjects (
    ProjectID INT PRIMARY KEY,
    ProjectName VARCHAR(255),
    VoluntaryRegistry VARCHAR(255),
    ARBProject VARCHAR(255),
    VoluntaryStatus VARCHAR(255),
    Scope VARCHAR(255),
    Type VARCHAR(255),
    ReductionRemoval VARCHAR(255),
    MethodologyProtocol VARCHAR(255),
    Region VARCHAR(255),
    Country VARCHAR(255),
    State VARCHAR(255),
    ProjectSiteLocation VARCHAR(255),
    ProjectDeveloper VARCHAR(255),
    TotalCreditsIssued INT,
    TotalCreditsRetired INT,
    TotalCreditsRemaining INT,
    TotalBufferPoolDeposits INT,
    ReversalsCoveredByBufferPool INT,
    ReversalsNotCoveredByBuffer INT,
    FirstYearOfProject INT,
    CreditsIssuedByVintageYear1996 INT,
    CreditsIssuedByVintageYear1997 INT,
    CreditsIssuedByVintageYear1998 INT,
    CreditsIssuedByVintageYear1999 INT,
    CreditsIssuedByVintageYear2000 INT,
    CreditsIssuedByVintageYear2001 INT,
    CreditsIssuedByVintageYear2002 INT,
    CreditsIssuedByVintageYear2003 INT,
    CreditsIssuedByVintageYear2004 INT,
    CreditsIssuedByVintageYear2005 INT,
    CreditsIssuedByVintageYear2006 INT,
    CreditsIssuedByVintageYear2007 INT,
    CreditsIssuedByVintageYear2008 INT,
    CreditsIssuedByVintageYear2009 INT,
    CreditsIssuedByVintageYear2010 INT,
    CreditsIssuedByVintageYear2011 INT,
    CreditsIssuedByVintageYear2012 INT,
    CreditsIssuedByVintageYear2013 INT,
    CreditsIssuedByVintageYear2014 INT,
    CreditsIssuedByVintageYear2015 INT,
    CreditsIssuedByVintageYear2016 INT,
    CreditsIssuedByVintageYear2017 INT,
    CreditsIssuedByVintageYear2018 INT,
    CreditsIssuedByVintageYear2019 INT,
    CreditsIssuedByVintageYear2020 INT,
    CreditsIssuedByVintageYear2021 INT,
    CreditsIssuedByVintageYear2022 INT,
    CreditsIssuedByVintageYear2023 INT,
    CreditsRetiredIn1996 INT,
    CreditsRetiredIn1997 INT,
    CreditsRetiredIn1998 INT,
    CreditsRetiredIn1999 INT,
    CreditsRetiredIn2000 INT,
    CreditsRetiredIn2001 INT,
    CreditsRetiredIn2002 INT,
    CreditsRetiredIn2003 INT,
    CreditsRetiredIn2004 INT,
    CreditsRetiredIn2005 INT,
    CreditsRetiredIn2006 INT,
    CreditsRetiredIn2007 INT,
    CreditsRetiredIn2008 INT,
    CreditsRetiredIn2009 INT,
    CreditsRetiredIn2010 INT,
    CreditsRetiredIn2011 INT,
    CreditsRetiredIn2012 INT,
    CreditsRetiredIn2013 INT,
    CreditsRetiredIn2014 INT,
    CreditsRetiredIn2015 INT,
    CreditsRetiredIn2016 INT,
    CreditsRetiredIn2017 INT,
    CreditsRetiredIn2018 INT,
    CreditsRetiredIn2019 INT,
    CreditsRetiredIn2020 INT,
    CreditsRetiredIn2021 INT,
    CreditsRetiredIn2022 INT,
    CreditsRetiredIn2023 INT,
    YearUnknown INT,
    CreditsRemainingByVintageYear1996 INT,
    CreditsRemainingByVintageYear1997 INT,
    CreditsRemainingByVintageYear1998 INT,
    CreditsRemainingByVintageYear1999 INT,
    CreditsRemainingByVintageYear2000 INT,
    CreditsRemainingByVintageYear2001 INT,
    CreditsRemainingByVintageYear2002 INT,
    CreditsRemainingByVintageYear2003 INT,
    CreditsRemainingByVintageYear2004 INT,
    CreditsRemainingByVintageYear2005 INT,
    CreditsRemainingByVintageYear2006 INT,
    CreditsRemainingByVintageYear2007 INT,
    CreditsRemainingByVintageYear2008 INT,
    CreditsRemainingByVintageYear2009 INT,
    CreditsRemainingByVintageYear2010 INT,
    CreditsRemainingByVintageYear2011 INT,
    CreditsRemainingByVintageYear2012 INT,
    CreditsRemainingByVintageYear2013 INT,
    CreditsRemainingByVintageYear2014 INT,
    CreditsRemainingByVintageYear2015 INT,
    CreditsRemainingByVintageYear2016 INT,
    CreditsRemainingByVintageYear2017 INT,
    CreditsRemainingByVintageYear2018 INT,
    CreditsRemainingByVintageYear2019 INT,
    CreditsRemainingByVintageYear2020 INT,
    CreditsRemainingByVintageYear2021 INT,
    CreditsRemainingByVintageYear2022 INT,
    CreditsRemainingByVintageYear2023 INT,
    ProjectOwner VARCHAR(255),
    OffsetProjectOperator VARCHAR(255),
    AuthorizedProjectDesignee VARCHAR(255),
    Verifier VARCHAR(255),
    EstimatedAnnualEmissionReductions INT,
    PERs VARCHAR(255),
    RegistryARB VARCHAR(255),
    ARBProjectDetail VARCHAR(255),
    ARBID INT,
    ProjectListed VARCHAR(255),
    ProjectRegistered VARCHAR(255),
    CCB_Certifications VARCHAR(255),
    ProjectType VARCHAR(255),
    RegistryDocuments VARCHAR(255),
    ProjectWebsite VARCHAR(255),
    CreditsIssuedByIssuanceYear1996 INT,
    CreditsIssuedByIssuanceYear1997 INT,
    CreditsIssuedByIssuanceYear1998 INT,
    CreditsIssuedByIssuanceYear1999 INT,
    CreditsIssuedByIssuanceYear2000 INT,
    CreditsIssuedByIssuanceYear2001 INT,
    CreditsIssuedByIssuanceYear2002 INT,
    CreditsIssuedByIssuanceYear2003 INT,
    CreditsIssuedByIssuanceYear2004 INT,
    CreditsIssuedByIssuanceYear2005 INT,
    CreditsIssuedByIssuanceYear2006 INT,
    CreditsIssuedByIssuanceYear2007 INT,
    CreditsIssuedByIssuanceYear2008 INT,
    CreditsIssuedByIssuanceYear2009 INT,
    CreditsIssuedByIssuanceYear2010 INT,
    CreditsIssuedByIssuanceYear2011 INT,
    CreditsIssuedByIssuanceYear2012 INT,
    CreditsIssuedByIssuanceYear2013 INT,
    CreditsIssuedByIssuanceYear2014 INT,
    CreditsIssuedByIssuanceYear2015 INT,
    CreditsIssuedByIssuanceYear2016 INT,
    CreditsIssuedByIssuanceYear2017 INT,
    CreditsIssuedByIssuanceYear2018 INT,
    CreditsIssuedByIssuanceYear2019 INT,
    CreditsIssuedByIssuanceYear2020 INT,
    CreditsIssuedByIssuanceYear2021 INT,
    CreditsIssuedByIssuanceYear2022 INT,
    CreditsIssuedByIssuanceYear2023 INT,
    NotesFromRegistry TEXT,
    NotesFromBerkeleyCarbonTradingProject TEXT,
    AddedToDatabaseVersion INT,
    RowsHaveEquations1 INT,
    RowsHaveEquations2 INT,
    FirstIssuanceYearNoHardCodeHide INT
);
