# docker-compose.yml

version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "4000:5432"
  
#  nodejs:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    volumes:
#      - .:/app
#    ports:
#      - "3000:3000"
#    depends_on:
#      - postgres
  
#  react:
#    image: node:14
#    working_dir: /app/client
#    command: npm start
#    volumes:
#      - ./client:/app/client
#    ports:
#      - "8000:8000"
#    depends_on:
#      - nodejs
