# docker-compose.yml

version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "4000:5432"
    networks:
      - app-network

  backend:
    build:
      context: ./server-nodejs
    container_name: backend-container
    environment:
      PGUSER: user
      PGHOST: postgres
      PGDATABASE: mydb
      PGPASSWORD: password
      PGPORT: 5432
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend-app
    container_name: frontend-container
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge